CareerSolutionsApp/Controllers/LoginEmpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CareerSolutionsApp.Controllers
{
    public class LoginEmpController : Controller
    {
        // GET: LoginEmp
        public ActionResult Login()
        {
            return View();
        }
    }
}

CareerSolutionsApp/Controllers/LoginJobSeekerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CareerSolutionsApp.Controllers
{
    public class LoginJobSeekerController : Controller
    {
        // GET: LoginJobSeeker
        public ActionResult Login()
        {
            return View();
        }
    }
}

CareerSolutionsApp/Controllers/WelcomeHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CareerSolutionsApp.Controllers
{
    public class WelcomeHomeController : Controller
    {
        // GET: WelcomeHome
        public ActionResult Welcome()
        {
            return View();
        }
       
    }
}

CareerSolutionsApp/Views/WelcomeHome/Welcome.cshtml
@{
    ViewBag.Title = "Welcome";
    Layout = "~/Views/Shared/_WelcomePage.cshtml";
}



<div>
    <h1 align="center">
        <font face="Lato" color="blue" size="8">@Html.ActionLink("JOBSEEKER", "Login", "LoginJobSeeker")</font>
    </h1>
    <hr />
    <hr />
    <h1 align="center">
        <font face="Lato" color="blue" size="8">@Html.ActionLink("EMPLOYEER", "Login", "LoginEmp")</font>
    </h1>
    <a></a>
</div>